# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(779, 400)
        Form.setMinimumSize(QtCore.QSize(681, 400))
        Form.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.window = QtWidgets.QTabWidget(Form)
        self.window.setGeometry(QtCore.QRect(0, 0, 811, 400))
        self.window.setMinimumSize(QtCore.QSize(681, 400))
        self.window.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.window.setObjectName("window")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.btnErfrischen = QtWidgets.QPushButton(self.tab_5)
        self.btnErfrischen.setGeometry(QtCore.QRect(680, 320, 81, 23))
        self.btnErfrischen.setStyleSheet("background-color: rgb(85, 0, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.btnErfrischen.setObjectName("btnErfrischen")
        self.tblErfrischen = QtWidgets.QTableWidget(self.tab_5)
        self.tblErfrischen.setGeometry(QtCore.QRect(30, 60, 641, 281))
        self.tblErfrischen.setRowCount(0)
        self.tblErfrischen.setColumnCount(6)
        self.tblErfrischen.setObjectName("tblErfrischen")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tblErfrischen.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 0, 191))
        self.tblErfrischen.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(85, 255, 127))
        self.tblErfrischen.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 248, 53))
        self.tblErfrischen.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(0, 170, 127))
        self.tblErfrischen.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 170, 0))
        self.tblErfrischen.setHorizontalHeaderItem(5, item)
        self.window.addTab(self.tab_5, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.btnSuche = QtWidgets.QPushButton(self.tab)
        self.btnSuche.setGeometry(QtCore.QRect(670, 320, 61, 23))
        self.btnSuche.setStyleSheet("background-color: rgb(85, 0, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.btnSuche.setObjectName("btnSuche")
        self.textCodeS = QtWidgets.QLineEdit(self.tab)
        self.textCodeS.setGeometry(QtCore.QRect(72, 51, 101, 20))
        self.textCodeS.setText("")
        self.textCodeS.setObjectName("textCodeS")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(21, 51, 45, 16))
        self.label.setObjectName("label")
        self.tblSuche = QtWidgets.QTableWidget(self.tab)
        self.tblSuche.setGeometry(QtCore.QRect(30, 90, 621, 261))
        self.tblSuche.setRowCount(0)
        self.tblSuche.setColumnCount(6)
        self.tblSuche.setObjectName("tblSuche")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tblSuche.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 0, 191))
        self.tblSuche.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(85, 255, 127))
        self.tblSuche.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 248, 53))
        self.tblSuche.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(0, 170, 127))
        self.tblSuche.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 170, 0))
        self.tblSuche.setHorizontalHeaderItem(5, item)
        self.window.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.btnHinzufugen = QtWidgets.QPushButton(self.tab_2)
        self.btnHinzufugen.setGeometry(QtCore.QRect(420, 260, 91, 21))
        self.btnHinzufugen.setStyleSheet("background-color: rgb(85, 0, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.btnHinzufugen.setObjectName("btnHinzufugen")
        self.layoutWidget = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget.setGeometry(QtCore.QRect(170, 70, 231, 211))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.textCodeH = QtWidgets.QLineEdit(self.layoutWidget)
        self.textCodeH.setObjectName("textCodeH")
        self.verticalLayout.addWidget(self.textCodeH)
        self.textNameH = QtWidgets.QLineEdit(self.layoutWidget)
        self.textNameH.setObjectName("textNameH")
        self.verticalLayout.addWidget(self.textNameH)
        self.textModellH = QtWidgets.QLineEdit(self.layoutWidget)
        self.textModellH.setObjectName("textModellH")
        self.verticalLayout.addWidget(self.textModellH)
        self.textPreisH = QtWidgets.QLineEdit(self.layoutWidget)
        self.textPreisH.setObjectName("textPreisH")
        self.verticalLayout.addWidget(self.textPreisH)
        self.textMengeH = QtWidgets.QLineEdit(self.layoutWidget)
        self.textMengeH.setObjectName("textMengeH")
        self.verticalLayout.addWidget(self.textMengeH)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.window.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.btnUpdate = QtWidgets.QPushButton(self.tab_3)
        self.btnUpdate.setGeometry(QtCore.QRect(530, 280, 71, 21))
        self.btnUpdate.setStyleSheet("background-color: rgb(85, 0, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.btnUpdate.setObjectName("btnUpdate")
        self.layoutWidget1 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget1.setGeometry(QtCore.QRect(270, 80, 251, 221))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_4.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_4.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_4.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_4.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_4.addWidget(self.label_11)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.textCodeU = QtWidgets.QLineEdit(self.layoutWidget1)
        self.textCodeU.setObjectName("textCodeU")
        self.verticalLayout_3.addWidget(self.textCodeU)
        self.textNameU = QtWidgets.QLineEdit(self.layoutWidget1)
        self.textNameU.setObjectName("textNameU")
        self.verticalLayout_3.addWidget(self.textNameU)
        self.textModellU = QtWidgets.QLineEdit(self.layoutWidget1)
        self.textModellU.setObjectName("textModellU")
        self.verticalLayout_3.addWidget(self.textModellU)
        self.textPreisU = QtWidgets.QLineEdit(self.layoutWidget1)
        self.textPreisU.setObjectName("textPreisU")
        self.verticalLayout_3.addWidget(self.textPreisU)
        self.textMengeU = QtWidgets.QLineEdit(self.layoutWidget1)
        self.textMengeU.setObjectName("textMengeU")
        self.verticalLayout_3.addWidget(self.textMengeU)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.tetxtIDU = QtWidgets.QLineEdit(self.tab_3)
        self.tetxtIDU.setGeometry(QtCore.QRect(30, 120, 180, 20))
        self.tetxtIDU.setObjectName("tetxtIDU")
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        self.label_13.setGeometry(QtCore.QRect(60, 80, 131, 39))
        self.label_13.setObjectName("label_13")
        self.idSuche = QtWidgets.QPushButton(self.tab_3)
        self.idSuche.setGeometry(QtCore.QRect(70, 150, 75, 23))
        self.idSuche.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.idSuche.setObjectName("idSuche")
        self.window.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.textIDD = QtWidgets.QLineEdit(self.tab_4)
        self.textIDD.setGeometry(QtCore.QRect(91, 50, 101, 20))
        self.textIDD.setText("")
        self.textIDD.setObjectName("textIDD")
        self.label_12 = QtWidgets.QLabel(self.tab_4)
        self.label_12.setGeometry(QtCore.QRect(60, 50, 31, 21))
        self.label_12.setObjectName("label_12")
        self.deleteOk = QtWidgets.QPushButton(self.tab_4)
        self.deleteOk.setGeometry(QtCore.QRect(200, 50, 91, 23))
        self.deleteOk.setStyleSheet("background-color: rgb(255, 0, 127);")
        self.deleteOk.setObjectName("deleteOk")
        self.btnDelete = QtWidgets.QPushButton(self.tab_4)
        self.btnDelete.setGeometry(QtCore.QRect(680, 280, 61, 23))
        self.btnDelete.setStyleSheet("background-color: rgb(85, 0, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.btnDelete.setObjectName("btnDelete")
        self.tblDelete = QtWidgets.QTableWidget(self.tab_4)
        self.tblDelete.setGeometry(QtCore.QRect(30, 80, 641, 231))
        self.tblDelete.setRowCount(0)
        self.tblDelete.setColumnCount(6)
        self.tblDelete.setObjectName("tblDelete")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tblDelete.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 0, 191))
        self.tblDelete.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(85, 255, 127))
        self.tblDelete.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 248, 53))
        self.tblDelete.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(0, 170, 127))
        self.tblDelete.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 170, 0))
        self.tblDelete.setHorizontalHeaderItem(5, item)
        self.window.addTab(self.tab_4, "")

        self.retranslateUi(Form)
        self.window.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "PRODUKT REGISTRIEREN"))
        self.btnErfrischen.setText(_translate("Form", "ERFISCHEN"))
        item = self.tblErfrischen.horizontalHeaderItem(0)
        item.setText(_translate("Form", "produktID"))
        item = self.tblErfrischen.horizontalHeaderItem(1)
        item.setText(_translate("Form", "produktCode"))
        item = self.tblErfrischen.horizontalHeaderItem(2)
        item.setText(_translate("Form", "produktName"))
        item = self.tblErfrischen.horizontalHeaderItem(3)
        item.setText(_translate("Form", "produktModell"))
        item = self.tblErfrischen.horizontalHeaderItem(4)
        item.setText(_translate("Form", "produktPreis"))
        item = self.tblErfrischen.horizontalHeaderItem(5)
        item.setText(_translate("Form", "produktMenge"))
        self.window.setTabText(self.window.indexOf(self.tab_5), _translate("Form", "PRODUKTE"))
        self.btnSuche.setText(_translate("Form", "SUCHE"))
        self.label.setText(_translate("Form", "CODE"))
        item = self.tblSuche.horizontalHeaderItem(0)
        item.setText(_translate("Form", "produktID"))
        item = self.tblSuche.horizontalHeaderItem(1)
        item.setText(_translate("Form", "produktCode"))
        item = self.tblSuche.horizontalHeaderItem(2)
        item.setText(_translate("Form", "produktName"))
        item = self.tblSuche.horizontalHeaderItem(3)
        item.setText(_translate("Form", "produktModell"))
        item = self.tblSuche.horizontalHeaderItem(4)
        item.setText(_translate("Form", "produktPreis"))
        item = self.tblSuche.horizontalHeaderItem(5)
        item.setText(_translate("Form", "produktMenge"))
        self.window.setTabText(self.window.indexOf(self.tab), _translate("Form", "PRODUKT SUCHE"))
        self.btnHinzufugen.setText(_translate("Form", "HINZUFUGEN"))
        self.label_2.setText(_translate("Form", "PRODUKTCODE"))
        self.label_3.setText(_translate("Form", "PRODUKTNAME"))
        self.label_4.setText(_translate("Form", "PRODUKTMODELL"))
        self.label_5.setText(_translate("Form", "PRODUKTPREIS"))
        self.label_6.setText(_translate("Form", "PRODUKTMENGE"))
        self.window.setTabText(self.window.indexOf(self.tab_2), _translate("Form", "PRODUKT HINZUFÜGEN"))
        self.btnUpdate.setText(_translate("Form", "UPDATE"))
        self.label_7.setText(_translate("Form", "PRODUKTCODE"))
        self.label_8.setText(_translate("Form", "PRODUKTNAME"))
        self.label_9.setText(_translate("Form", "PRODUKTMODELL"))
        self.label_10.setText(_translate("Form", "PRODUKTPREIS"))
        self.label_11.setText(_translate("Form", "PRODUKTMENGE"))
        self.label_13.setText(_translate("Form", "PRODUKT-ID EINGEBEN"))
        self.idSuche.setText(_translate("Form", "SUCHE"))
        self.window.setTabText(self.window.indexOf(self.tab_3), _translate("Form", "PRODUKT UPDATE"))
        self.label_12.setText(_translate("Form", "ID"))
        self.deleteOk.setText(_translate("Form", "OK"))
        self.btnDelete.setText(_translate("Form", "DELETE"))
        item = self.tblDelete.horizontalHeaderItem(0)
        item.setText(_translate("Form", "produktID"))
        item = self.tblDelete.horizontalHeaderItem(1)
        item.setText(_translate("Form", "produktCode"))
        item = self.tblDelete.horizontalHeaderItem(2)
        item.setText(_translate("Form", "produktName"))
        item = self.tblDelete.horizontalHeaderItem(3)
        item.setText(_translate("Form", "produktModell"))
        item = self.tblDelete.horizontalHeaderItem(4)
        item.setText(_translate("Form", "produktPreis"))
        item = self.tblDelete.horizontalHeaderItem(5)
        item.setText(_translate("Form", "produktMenge"))
        self.window.setTabText(self.window.indexOf(self.tab_4), _translate("Form", "PRODUKT LÖSCHUNG"))

